[package]
name = "plotters"
version = "0.2.14"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A Rust drawing library focus on data plotting for both WASM and native applications"
repository = "https://github.com/38/plotters"
keywords = ["WebAssembly", "Visualization", "Plotting", "Drawing"]
categories = ["visualization", "wasm"]
readme = "README.md"
exclude = ["doc-template/*"]

[dependencies]
num-traits = "0.2.11"
chrono = { version = "0.4.11", optional = true }
gif = { version = "0.10.3", optional = true }

[dependencies.palette]
version = "0.5.0"
default-features = false
optional = true
features = ["std"]



[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rusttype = { version = "0.8.2", optional = true }
lazy_static = { version = "1.4.0", optional = true }
font-kit = { version = "0.6.0", optional = true }
piston_window = { version = "0.108.0", optional = true }
iced = { git = "https://github.com/topo-finance/iced", optional = true, features = ["canvas"] }
iced_native = { version = "0.2", optional = true }
iced_wgpu = { version = "0.2", optional = true }
iced_core = { version = "0.2", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.image]
version = "0.23.4"
optional = true
default-features = false
features = ["jpeg", "png", "bmp"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.cairo-rs]
version = "0.8.1"
optional = true
features = ["ps"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys= "0.3.39"
wasm-bindgen = "0.2.62"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.39"
features = ['Document', 'DomRect', 'Element', 'HtmlElement', 'Node', 'Window', 'HtmlCanvasElement', 'CanvasRenderingContext2d']

[features]
default = ["image_encoder", "svg", "chrono", "palette_ext", "gif_backend",
		   "deprecated_items", "bitmap", "ttf", "errorbar", "candlestick",
		   "boxplot", "histogram", "area_series", "line_series", "point_series"]
ttf = ["font-kit", "rusttype", "lazy_static"]
image_encoder = ["image", "bitmap"]
palette_ext = ["palette"]
gif_backend = ["gif", "bitmap"]
datetime = ["chrono"]
svg = []
evcxr = ["svg"]
piston = ["piston_window", "ttf"]
cairo = ["cairo-rs", "ttf"]
bitmap = ["ttf"]
deprecated_items = [] # Keep some of the deprecated items for backward compatibility
debug = [] # Enable debugging code
errorbar = []
candlestick = []
boxplot = []
histogram = []
area_series = []
line_series = []
point_series = []
iced_back = ["iced", "iced_wgpu", "iced_native", "iced_core"]

[dev-dependencies]
rand = "0.7.3"
itertools = "0.9.0"
rand_distr = "0.2.2"
criterion = "0.3.2"
rayon = "1.3.0"
rand_xorshift = "0.2.0"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.12"

[[bench]]
name = "benchmark"
harness = false
path = "benches/main.rs"

[profile.bench]
debug = true
